stages:
  - prepare
  - build

prepare:
  stage: prepare
  image: python:3.6
  script:
    - apt-get update && apt-get install -y re2c
    - git submodule update --init --recursive
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install cython
    - re2c -d -b -o lib/parse_date.c lib/parse_date.re
    - cython --directive language_level=3 strtotime.pyx
    - python setup.py build sdist
  artifacts:
    untracked: true

wheel:
  stage: build
  image: quay.io/pypa/manylinux2014_x86_64
  dependencies:
    - prepare
  script:
    - ./build.sh
  artifacts:
    paths:
      - dist/*.zip
      - dist/*manylinux*whl
