stages:
  - prepare
  - build
  - repair

prepare:
  stage: prepare
  image: python:latest
  script:
    - apt-get update && apt-get install re2c
    - git submodule update --init --recursive
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install cython
    - re2c -d -b -o lib/parse_date.c lib/parse_date.re
    - cython --directive language_level=3 strtotime.pyx
  artifacts:
    untracked: true

cp34_x64:
  stage: build
  image: quay.io/pypa/manylinux1_x86_64
  dependencies:
    - prepare
  script:
    - /opt/python/cp34-cp34m/pip wheel . -w dist
  artifacts:
    paths:
      - dist/*whl
